# kotlinx.serialization
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**
-keepclassmembers class kotlinx.serialization.json.** { *** Companion; }
-keepclasseswithmembers class kotlinx.serialization.json.** { kotlinx.serialization.KSerializer serializer(...); }
-keep,includedescriptorclasses class com.spectraseq.app.**$$serializer { *; }
-keepclassmembers class com.spectraseq.app.** { *** Companion; }
-keepclasseswithmembers class com.spectraseq.app.** { kotlinx.serialization.KSerializer serializer(...); }
-keep,includedescriptorclasses class com.spectraseq.core.**$$serializer { *; }
-keepclassmembers class com.spectraseq.core.** { *** Companion; }
-keepclasseswithmembers class com.spectraseq.core.** { kotlinx.serialization.KSerializer serializer(...); }
