# kotlinx.serialization
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.**
-keepclassmembers class kotlinx.serialization.json.** { *** Companion; }
-keepclasseswithmembers class kotlinx.serialization.json.** { kotlinx.serialization.KSerializer serializer(...); }
-keep,includedescriptorclasses class com.notemove.app.**$$serializer { *; }
-keepclassmembers class com.notemove.app.** { *** Companion; }
-keepclasseswithmembers class com.notemove.app.** { kotlinx.serialization.KSerializer serializer(...); }
-keep,includedescriptorclasses class com.notemove.core.**$$serializer { *; }
-keepclassmembers class com.notemove.core.** { *** Companion; }
-keepclasseswithmembers class com.notemove.core.** { kotlinx.serialization.KSerializer serializer(...); }
